
export type JAIL_NAME = 'RICHMOND_CITY_JAIL' | 'HENRICO_COUNTY_REGIONAL_JAIL';

type JAIL_NAMES = {
    [K in JAIL_NAME]?: string
}

export const JAILS: JAIL_NAMES = {
  RICHMOND_CITY_JAIL: 'RICHMOND CITY JAIL',
  HENRICO_COUNTY_REGIONAL_JAIL: 'HENRICO COUNTY REGIONAL JAIL' 
};

export const JAIL_URLS = {
  RICHMOND_CITY_JAIL: 'https://omsweb.secure-gps.com/jtclientweb/jailtracker/index/Richmond_Co_VA',
  HENRICO_COUNTY_REGIONAL_JAIL: 'https://ppd.henrico.us/searcharrest.aspx' 
};

export const MIDLOTHIAN_CHARGES = {
  LARCENY_PETIT_SHOPLIFTING: 'LARCENY-PETIT-SHOPLIFTING',
  LARCENY_GRAND_SHOPLIFTING: 'LARCENY-GRAND-SHOPLIFTING',
  OTHER_OFFENSES_VIOLATE_PO_DOMESTIC: 'OTHER OFFENSES-VIOLATE PO-DOMESTIC',
  SEX_OFFENSES_EXPOSING_PERSON: 'SEX OFFENSES-EXPOSING PERSON',
  OTHER_STATE_VIOLATIONS_CRIMINAL: 'OTHER STATE VIOLATIONS-CRIMINAL',
  OTHER_OFFENSES_PROBATION_VIOLATION: 'OTHER OFFENSES-PROBATION VIOLATION',
  OTHER_OFFENSES_CONTEMPT_OF_COURT: 'OTHER OFFENSES-CONTEMPT OF COURT',
  DRUG_VIOL_NON_NARC_POSSESS: 'DRUG VIOL-NON NARC-POSSESS',
  ASSAULT_NON_AGGRAVATED: 'ASSAULT-NON-AGGRAVATED',
  OTHER_ASSAULTS_OBSTRUCT_JUSTICE: 'OTHER ASSAULTS-OBSTRUCT JUSTICE',
  POSSESSION_OF_COCAINE: 'POSSESSION OF COCAINE',
  VIOLATON_OF_PROTECTIVE_ORDER_NON_DOMESTIC: 'VIOLATON OF PROTECTIVE ORDER - NON DOMESTIC'
};

export const RICHMOND_CHARGES = {
  OBSTRUCTION_OF_JUSTICE: 'OBSTRUCTION OF JUSTICE', 
  WEAPONS_CARRY_CONCEALED_WEAPON_OTHER_THAN_FIREARM: 'WEAPONS CARRY CONCEALED WEAPON - OTHER THAN FIREARM', 
  WEAPONS_BRANDISH_MACHETE_OR_BLADED_WEAPON: 'WEAPONS BRANDISH MACHETE OR BLADED WEAPON', 
  ASSAULT_SIMPLE_ASSAULT_ON_LAW_ENFORCEMENT: 'ASSAULT_SIMPLE_ASSAULT_ON_LAW_ENFORCEMENT', 
  ASSAULT_SIMPLE_ASSAULT_AGAINST_FAMILY_MEMBER: 'ASSAULT_SIMPLE_ASSAULT_AGAINST_FAMILY_MEMBER'
};